### ISSUE TITLE
I find my plot is discontinuous

### ISSUE THREAD

**Issue by yuanzunli** [williamjameshandley/fgivenx#3]
I'm using fgivenx to make plots from GetDist chains. But I find my curve is discontinuous for the part where the uncertainty region is relatively narrow.  I try to take more values for X axis, i.e.,  let
k=numpy.logspace(23,30,500)， instead of k=numpy.logspace(23,30,100)，
but it did not improve the result significantly. Could you help me and check the problem?

![planck](https://user-images.githubusercontent.com/44826550/63496930-5eeaf980-c4f5-11e9-943a-cb860851fa69.png)

In addition, as you see, the fgivenx plot the entire sigma regions. Could I just
plot the 1 sigma region for my function? Thanks very much.

Below is my python code:
#######################################################################
```python
import numpy as np
import matplotlib.pyplot as plt
from fgivenx import plot_contours, samples_from_getdist_chains

file_root = './bb/test'
samples, weights = samples_from_getdist_chains(['p1','p2','p3','p4','p5','p6','p7','p8','p9','p10'], file_root)
print(type(samples))
print(np.size(samples))
print(np.shape(samples))

z=1.0
nbin=500

def phi(z,L,theta):
    p1,p2,p3,p4,p5,p6,p7,p8,p9,p10 = theta
    rho=1.0/( ((1+p1)/(1+z))**p5 + ((1+p1)/(1+z))**p6 ) * ( ((1+p1)/(1+0.0))**p5 + ((1+p1)/(1+0.0))**p6 )
    e_z=(1+z)**p8
    L_z=10**p4*e_z
    result= 10**p7 * rho * (10**L/L_z)**(-p2)*np.exp(-(10**L/L_z)**p3)
    return result


def log10phi(z,k,theta):
    y=np.empty(nbin)
    for i in range(0,nbin):
        y[i]=np.log10(phi(z, k[i], theta) )
    return y


def PPS(k, theta):
    return log10phi(z,k,theta)

k = np.linspace(23.0, 30.0, nbin)
cbar = plot_contours(PPS, k, samples, weights=weights)
cbar = plt.colorbar(cbar,ticks=[0,1,2,3])
cbar.set_ticklabels(['',r'$1\sigma$',r'$2\sigma$',r'$3\sigma$'])
plt.ylabel(r'$\ln\left(10^{10}\mathcal{P}_\mathcal{R}\right)$')
plt.xlabel(r'$k / {\rm Mpc}^{-1}$')
plt.tight_layout()
plt.savefig('planck.png')
```

**Comment by williamjameshandley** [comment]
Hi @yuanzunli. Could you edit the above post to include a representative picture of the problem? (click the top-right menu to edit, and then drag the image file into the box, or click the bottom bar of the editor).

**Comment by yuanzunli** [comment]
Hi @williamjameshandley. I have updated the issue.

**Comment by williamjameshandley** [comment]
@yuanzunli In this case one wouldn't expect increasing the number of samples in the x-coordinate to help matters, since the issue resides in the paucity of y-samples. If you increase the number of samples in the y direction to more than 500 do you get better results?

You will likely get better perfomance by replacing the loop over y values in `log10phi` with a vectorised operation, which as far as I can tell would amount to:

```python
def log10phi(z,k,theta):
    return np.log10(phi(z, k, theta) )
```  

I also modified your original post so that the [code formatting is easier to read](https://guides.github.com/features/mastering-markdown/) -- if you surround the code in triple backticks, rather than each line with single backticks then you get a nicer block formatting and syntax highlighting

**Comment by yuanzunli** [comment]
@williamjameshandley I replaced the loop over y values in log10phi with your suggested operation, but the result seems to be the same as the old one.

**Comment by williamjameshandley** [comment]
Did you increase the number of samples in y? The equivalent code would be 

```python
cbar = plot_contours(PPS, k, samples, weights=weights, ny=1000) # Default ny is 100
```

**Comment by yuanzunli** [comment]
I increased both the numbers of samples in x and y.  
```Python
nbin=500
k = np.linspace(23.0, 30.0, nbin)
cbar = plot_contours(PPS, k, samples, weights=weights, ny=500)
```
![planck](https://user-images.githubusercontent.com/44826550/63508437-8bf6d680-c50c-11e9-9abd-bb080eabe5d7.png)
Now the result seems to be nice. Thanks very much for your help @williamjameshandley

**Comment by williamjameshandley** [comment]
Many thanks @yuanzunli

**Comment by yuanzunli** [comment]
I find there are some black lines in the  fgivenx plot, which define the different sigma regions. For my figure, the uncertainty band is narrow, and these black lines may make the figure look crowded. Could I remove these black lines？

**Comment by williamjameshandley** [comment]
If you pass `lines=false` this kwarg should be forwarded onto fgivenx.plot.plot
