### ISSUE TITLE
handling a piecewise function

### ISSUE THREAD

**Issue by surgithub** [williamjameshandley/fgivenx#4]
Please describe how to deal with a piecewise function in fgivenx. Thanks.

**Comment by williamjameshandley** [comment]
Hi @surgithub. Could you give me a bit more detail about how you've currently tried to do this? One way to implement a vectorisable piecewise function is using a `numpy.where` construction:

```python
def f(x, theta):
    m0, c0, m1, c1 = theta
    y = np.where(x<0, m0*x + c0, m1*x + c1)
    return y
```

would implement a function that is piecewise linear either side of zero, but without more detail about the kind of piecewise function you're trying to implement I'm not sure if this is what you're looking for.

**Comment by surgithub** [comment]
It is working now. Thank you. One more point: How to ignore the initial rows from the samples, or is there any command in fgivenx to remove initial fraction of samples, something like the following command of getdist
`settings={'ignore_rows':0.3}`

**Comment by williamjameshandley** [comment]
OK,

**Comment by surgithub** [comment]
Thank you.
