### ISSUE TITLE
some queries

### ISSUE THREAD

**Issue by surgithub** [williamjameshandley/fgivenx#7]
(i) Is there any way to print mean value and the corresponding one sigma errors of f(x) for a given value of x?
(ii) Can we explicitly print a table of points on the upper or lower one sigma curve?

Thanks.

**Comment by williamjameshandley** [comment]
Hi @surgithub -- apologies these queries slipped through the net. This should be pretty straightforward to compute, you just need to use the driving routine `fgivenx.drivers.compute_samples` to answer (i):

```python
from fgivenx.drivers import compute_samples
fsamps = compute_samples(f, x, samples)
means = fsamps.mean(axis=1)
stds = fsamps.std(axis=1)
```
(this code should work for the example in the README).

Answering (ii) is a little bit more fiddly, (as these are not quite the same thing as the contour lines) , but the information you need is contained in the outputs of `compute_pmf` which gives you the probability mass function (called in the same manner as `compute_samples`, which can be converted into iso-probability contour lines. You can see this in action in `fgivenx.drivers.plot_contours`, which calls `compute_pmf` followed by `fgivenx.plot.plot`
